services:
  api:
    image: ogna-py-appi:prod
    container_name: api
    restart: unless-stopped # Add restart policy
    depends_on:
      - postgres
      - kong-cp
    expose:
      - "8000"
    networks:
      - gql
      - api
    env_file:
      - .env
